name: ci
on: 
  push: 
     branches: 
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mthbest-sudo/AliBabaScraper
  env_path: ./env
  flight_path: /env/flight.json
  train_path: /env/train.json
  
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Node Repos
        uses: actions/setup-node@v4
        with: 
          node-version: '18.18.2'
      - run: npm ci 
      - run: npm run start 

